import {
  formatApprovalStatus,
  formatCloseStatus,
  formatDateOnly,
  formatDateTime,
  formatEventType,
  formatLeaveLedgerEntryType,
  formatReceiveStatus,
  formatTimeOnly,
  formatWorkMinutes,
} from "@/lib/api";
import type { AttendanceSectionProps } from "@/components/dashboard-sections/attendance/attendance-section-types";
import type { LeaveSectionProps, UseDashboardSectionPropsParams } from "@/hooks/dashboard-section-props/types";

export function buildAttendanceSectionProps(params: UseDashboardSectionPropsParams): AttendanceSectionProps {
  return {
    data: {
      dashboard: params.dashboard,
      attendanceDecisionResult: params.attendanceDecisionResult,
      attendanceCloseResult: params.attendanceCloseResult,
      reportMonth: params.reportMonth,
      reportFrom: params.reportFrom,
      reportTo: params.reportTo,
      activePanel: params.currentSubNavId,
    },
    filters: {
      attendanceFilterMonth: params.attendanceFilterMonth,
      attendanceFilterEmployeeCode: params.attendanceFilterEmployeeCode,
      attendanceFilterDepartmentName: params.attendanceFilterDepartmentName,
      attendanceApprovalStatus: params.attendanceApprovalStatus,
      attendanceEventFrom: params.attendanceEventFrom,
      attendanceEventTo: params.attendanceEventTo,
      attendanceDecisionComment: params.attendanceDecisionComment,
      attendanceErrorCode: params.attendanceErrorCode,
      attendanceErrorHandlingStatus: params.attendanceErrorHandlingStatus,
      attendanceMonthCloseApprovalStatus: params.attendanceMonthCloseApprovalStatus,
      attendanceMonthCloseStatusFilter: params.attendanceMonthCloseStatusFilter,
    },
    actions: {
      onAttendanceFilterMonthChange: params.setAttendanceFilterMonth,
      onAttendanceFilterEmployeeCodeChange: params.setAttendanceFilterEmployeeCode,
      onAttendanceFilterDepartmentNameChange: params.setAttendanceFilterDepartmentName,
      onAttendanceApprovalStatusChange: params.setAttendanceApprovalStatus,
      onAttendanceEventFromChange: params.setAttendanceEventFrom,
      onAttendanceEventToChange: params.setAttendanceEventTo,
      onAttendanceDecisionCommentChange: params.setAttendanceDecisionComment,
      onAttendanceErrorCodeChange: params.setAttendanceErrorCode,
      onAttendanceErrorHandlingStatusChange: params.setAttendanceErrorHandlingStatus,
      onAttendanceMonthCloseApprovalStatusChange: params.setAttendanceMonthCloseApprovalStatus,
      onAttendanceMonthCloseStatusFilterChange: params.setAttendanceMonthCloseStatusFilter,
      onApplyAttendanceFilters: params.applyAttendanceFilters,
      onResetAttendanceFilters: params.resetAttendanceFilters,
      onAttendanceMonthClose: params.handleAttendanceMonthClose,
      onAttendanceDecision: params.handleAttendanceDecision,
      onAttendanceDailyEditRequestDecision: params.handleAttendanceDailyEditRequestDecision,
      onBulkAttendanceDecision: params.handleBulkAttendanceDecision,
      onAttendanceErrorStatus: params.handleAttendanceErrorStatus,
      onDownloadMonthlyAttendanceCsv: params.handleMonthlyAttendanceCsvDownload,
      onDownloadDailyAttendanceCsv: params.handleDailyAttendanceCsvDownload,
      onDownloadDailyAttendancePdf: params.handleDailyAttendancePdfDownload,
    },
    formatters: {
      formatDateOnly,
      formatDateTime,
      formatTimeOnly,
      formatWorkMinutes,
      formatApprovalStatus,
      formatCloseStatus,
      formatEventType,
      formatReceiveStatus,
    },
  };
}

export function buildLeaveSectionProps(params: UseDashboardSectionPropsParams): LeaveSectionProps {
  return {
    data: {
      dashboard: params.dashboard,
      decisionResult: params.decisionResult,
      leaveAdminResult: params.leaveAdminResult,
      activePanel: params.currentSubNavId,
    },
    filters: {
      workProcedureStatus: params.workProcedureStatus,
      workProcedureEmployeeCode: params.workProcedureEmployeeCode,
      workProcedureDepartmentName: params.workProcedureDepartmentName,
      workProcedureLeaveTypeCode: params.workProcedureLeaveTypeCode,
      workProcedureRequestCategory: params.workProcedureRequestCategory,
      workProcedureTimeLeaveType: params.workProcedureTimeLeaveType,
      workProcedureFrom: params.workProcedureFrom,
      workProcedureTo: params.workProcedureTo,
    },
    form: {
      grantEmployeeId: params.grantEmployeeId,
      grantDays: params.grantDays,
      grantDate: params.grantDate,
      grantExpiresOn: params.grantExpiresOn,
      grantNote: params.grantNote,
      adjustType: params.adjustType,
      adjustDays: params.adjustDays,
      adjustDate: params.adjustDate,
      adjustNote: params.adjustNote,
      decisionComment: params.decisionComment,
    },
    actions: {
      onWorkProcedureStatusChange: params.setWorkProcedureStatus,
      onWorkProcedureEmployeeCodeChange: params.setWorkProcedureEmployeeCode,
      onWorkProcedureDepartmentNameChange: params.setWorkProcedureDepartmentName,
      onWorkProcedureLeaveTypeCodeChange: params.setWorkProcedureLeaveTypeCode,
      onWorkProcedureRequestCategoryChange: params.setWorkProcedureRequestCategory,
      onWorkProcedureTimeLeaveTypeChange: params.setWorkProcedureTimeLeaveType,
      onWorkProcedureFromChange: params.setWorkProcedureFrom,
      onWorkProcedureToChange: params.setWorkProcedureTo,
      onGrantEmployeeIdChange: params.setGrantEmployeeId,
      onGrantDaysChange: params.setGrantDays,
      onGrantDateChange: params.setGrantDate,
      onGrantExpiresOnChange: params.setGrantExpiresOn,
      onGrantNoteChange: params.setGrantNote,
      onAdjustTypeChange: params.setAdjustType,
      onAdjustDaysChange: params.setAdjustDays,
      onAdjustDateChange: params.setAdjustDate,
      onAdjustNoteChange: params.setAdjustNote,
      onDecisionCommentChange: params.setDecisionComment,
      onApplyWorkProcedureFilters: params.applyWorkProcedureFilters,
      onResetWorkProcedureFilters: params.resetWorkProcedureFilters,
      onWorkProcedureDecision: params.handleWorkProcedureDecision,
      onBulkWorkProcedureDecision: params.handleBulkWorkProcedureDecision,
      onGrantPaidLeave: params.handleGrantPaidLeave,
      onAdjustPaidLeave: params.handleAdjustPaidLeave,
    },
    formatters: {
      formatDateOnly,
      formatDateTime,
      formatApprovalStatus,
      formatLeaveLedgerEntryType,
    },
  };
}
