import type { AttendanceSectionProps } from "@/components/dashboard-sections/attendance/attendance-section-types";
import type { AuditSection } from "@/components/dashboard-sections/audit-section";
import type { CardsSection } from "@/components/dashboard-sections/cards-section";
import type { DashboardOverviewSection } from "@/components/dashboard-sections/dashboard-overview-section";
import type { EmployeePortalSectionProps } from "@/components/dashboard-sections/employee-portal/employee-portal-types";
import type { EmployeesSection } from "@/components/dashboard-sections/employees-section";
import type { LeaveSection } from "@/components/dashboard-sections/leave-section";
import type { NoticesSection } from "@/components/dashboard-sections/notices-section";
import type { PayrollSectionProps } from "@/components/dashboard-sections/payroll/payroll-section-types";
import type { ReportsSection } from "@/components/dashboard-sections/reports-section";
import type { SystemSection } from "@/components/dashboard-sections/system-section";
import type {
  AuthAudience,
  AttendanceDailyEditRequestCreatePayload,
  CurrentUser,
  DashboardData,
  EmployeePortalData,
  EmployeeUpdatePayload,
  ImportHistory,
  LeaveRequestCreatePayload,
  PayrollDataDefinition,
  PayrollImportBatch,
  PayrollImportBatchDetail,
  PayrollStatement,
  PayrollStatementDetail,
} from "@/types";

export type { EmployeePortalSectionProps };

export type DashboardOverviewSectionProps = Parameters<typeof DashboardOverviewSection>[0];
export type EmployeesSectionProps = Parameters<typeof EmployeesSection>[0];
export type CardsSectionProps = Parameters<typeof CardsSection>[0];
export type LeaveSectionProps = Parameters<typeof LeaveSection>[0];
export type NoticesSectionProps = Parameters<typeof NoticesSection>[0];
export type ReportsSectionProps = Parameters<typeof ReportsSection>[0];
export type SystemSectionProps = Parameters<typeof SystemSection>[0];
export type AuditSectionProps = Parameters<typeof AuditSection>[0];

type SetValue<T> = (value: T) => void;

export type UseDashboardSectionPropsParams = {
  dashboard: DashboardData;
  employeePortal: EmployeePortalData;
  currentUser: CurrentUser | null;
  currentAudience: AuthAudience | "";
  currentSubNavId: string;
  isPending: boolean;
  errorMessage: string;
  canUseEmployeePortal: boolean;
  employeeImportResult: string;
  systemResult: string;
  assignEmployeeId: string;
  assignCardUid: string;
  assignResult: string;
  attendanceDecisionComment: string;
  attendanceDecisionResult: string;
  attendanceCloseResult: string;
  attendanceFilterMonth: string;
  attendanceFilterEmployeeCode: string;
  attendanceFilterDepartmentName: string;
  attendanceApprovalStatus: string;
  attendanceEventFrom: string;
  attendanceEventTo: string;
  attendanceErrorCode: string;
  attendanceErrorHandlingStatus: string;
  attendanceMonthCloseApprovalStatus: string;
  attendanceMonthCloseStatusFilter: string;
  decisionComment: string;
  decisionResult: string;
  grantEmployeeId: string;
  grantDays: string;
  grantDate: string;
  grantExpiresOn: string;
  grantNote: string;
  adjustType: "ADJUST_PLUS" | "ADJUST_MINUS";
  adjustDays: string;
  adjustDate: string;
  adjustNote: string;
  leaveAdminResult: string;
  workProcedureStatus: string;
  workProcedureEmployeeCode: string;
  workProcedureDepartmentName: string;
  workProcedureLeaveTypeCode: string;
  workProcedureRequestCategory: string;
  workProcedureTimeLeaveType: string;
  workProcedureFrom: string;
  workProcedureTo: string;
  noticeType: string;
  noticeTitle: string;
  noticeBody: string;
  noticeStartAt: string;
  noticeEndAt: string;
  noticeResult: string;
  payrollTypeLabel: string;
  filteredPayrollDefinitions: PayrollDataDefinition[];
  filteredPayrollBatches: PayrollImportBatch[];
  filteredPayrollStatements: PayrollStatement[];
  filteredPayrollHistory: ImportHistory[];
  selectedPayrollBatchDetail: PayrollImportBatchDetail | null;
  selectedAdminPayrollDetail: PayrollStatementDetail | null;
  selectedEmployeePayrollDetail: PayrollStatementDetail | null;
  payrollResult: string;
  payrollDefinitionResult: string;
  payrollBatchResult: string;
  payrollStatementType: "PAYROLL" | "BONUS";
  payrollDefinitionId: string;
  payrollDefinitionName: string;
  payrollDefinitionActive: boolean;
  payrollTargetYearMonth: string;
  payrollPeriodStartOn: string;
  payrollPeriodEndOn: string;
  payrollPayDate: string;
  payrollPublishDate: string;
  payrollRemarks: string;
  payrollBatchTargetMonthFilter: string;
  payrollBatchEmployeeCodeFilter: string;
  payrollBatchEmployeeNameFilter: string;
  reportFileHistory: ImportHistory[];
  reportMonth: string;
  reportFrom: string;
  reportTo: string;
  reportEmployeeId: string;
  reportResult: string;
  auditActorFilter: string;
  auditActionFilter: string;
  auditFrom: string;
  auditTo: string;
  setAssignEmployeeId: SetValue<string>;
  setAssignCardUid: SetValue<string>;
  setAttendanceFilterMonth: SetValue<string>;
  setAttendanceFilterEmployeeCode: SetValue<string>;
  setAttendanceFilterDepartmentName: SetValue<string>;
  setAttendanceApprovalStatus: SetValue<string>;
  setAttendanceEventFrom: SetValue<string>;
  setAttendanceEventTo: SetValue<string>;
  setAttendanceDecisionComment: SetValue<string>;
  setAttendanceErrorCode: SetValue<string>;
  setAttendanceErrorHandlingStatus: SetValue<string>;
  setAttendanceMonthCloseApprovalStatus: SetValue<string>;
  setAttendanceMonthCloseStatusFilter: SetValue<string>;
  setWorkProcedureStatus: SetValue<string>;
  setWorkProcedureEmployeeCode: SetValue<string>;
  setWorkProcedureDepartmentName: SetValue<string>;
  setWorkProcedureLeaveTypeCode: SetValue<string>;
  setWorkProcedureRequestCategory: SetValue<string>;
  setWorkProcedureTimeLeaveType: SetValue<string>;
  setWorkProcedureFrom: SetValue<string>;
  setWorkProcedureTo: SetValue<string>;
  setGrantEmployeeId: SetValue<string>;
  setGrantDays: SetValue<string>;
  setGrantDate: SetValue<string>;
  setGrantExpiresOn: SetValue<string>;
  setGrantNote: SetValue<string>;
  setAdjustType: SetValue<"ADJUST_PLUS" | "ADJUST_MINUS">;
  setAdjustDays: SetValue<string>;
  setAdjustDate: SetValue<string>;
  setAdjustNote: SetValue<string>;
  setDecisionComment: SetValue<string>;
  setNoticeType: SetValue<string>;
  setNoticeTitle: SetValue<string>;
  setNoticeBody: SetValue<string>;
  setNoticeStartAt: SetValue<string>;
  setNoticeEndAt: SetValue<string>;
  setPayrollStatementType: SetValue<"PAYROLL" | "BONUS">;
  setPayrollDefinitionId: SetValue<string>;
  setPayrollDefinitionName: SetValue<string>;
  setPayrollDefinitionActive: SetValue<boolean>;
  setPayrollTargetYearMonth: SetValue<string>;
  setPayrollPeriodStartOn: SetValue<string>;
  setPayrollPeriodEndOn: SetValue<string>;
  setPayrollPayDate: SetValue<string>;
  setPayrollPublishDate: SetValue<string>;
  setPayrollRemarks: SetValue<string>;
  setPayrollBatchTargetMonthFilter: SetValue<string>;
  setPayrollBatchEmployeeCodeFilter: SetValue<string>;
  setPayrollBatchEmployeeNameFilter: SetValue<string>;
  setReportMonth: SetValue<string>;
  setReportFrom: SetValue<string>;
  setReportTo: SetValue<string>;
  setReportEmployeeId: SetValue<string>;
  setAuditActorFilter: SetValue<string>;
  setAuditActionFilter: SetValue<string>;
  setAuditFrom: SetValue<string>;
  setAuditTo: SetValue<string>;
  handleRefresh: () => void;
  handleLogout: () => void;
  handlePortalModeChange: (mode: AuthAudience) => void;
  handleEmployeeImport: EmployeesSectionProps["actions"]["onEmployeeImport"];
  handleTemplateDownload: (kind: "employees" | "payroll" | "bonus") => Promise<void>;
  handleEmployeeUpdate: (id: number, payload: EmployeeUpdatePayload) => Promise<void>;
  handleAssignCard: CardsSectionProps["actions"]["onAssignCard"];
  handleRevokeCard: CardsSectionProps["actions"]["onRevokeCard"];
  handleDeleteCard: CardsSectionProps["actions"]["onDeleteCard"];
  applyAttendanceFilters: AttendanceSectionProps["actions"]["onApplyAttendanceFilters"];
  resetAttendanceFilters: AttendanceSectionProps["actions"]["onResetAttendanceFilters"];
  handleAttendanceMonthClose: AttendanceSectionProps["actions"]["onAttendanceMonthClose"];
  handleAttendanceDecision: AttendanceSectionProps["actions"]["onAttendanceDecision"];
  handleAttendanceDailyEditRequestDecision: AttendanceSectionProps["actions"]["onAttendanceDailyEditRequestDecision"];
  handleBulkAttendanceDecision: AttendanceSectionProps["actions"]["onBulkAttendanceDecision"];
  handleAttendanceErrorStatus: AttendanceSectionProps["actions"]["onAttendanceErrorStatus"];
  applyWorkProcedureFilters: LeaveSectionProps["actions"]["onApplyWorkProcedureFilters"];
  resetWorkProcedureFilters: LeaveSectionProps["actions"]["onResetWorkProcedureFilters"];
  handleWorkProcedureDecision: LeaveSectionProps["actions"]["onWorkProcedureDecision"];
  handleBulkWorkProcedureDecision: LeaveSectionProps["actions"]["onBulkWorkProcedureDecision"];
  handleGrantPaidLeave: LeaveSectionProps["actions"]["onGrantPaidLeave"];
  handleAdjustPaidLeave: LeaveSectionProps["actions"]["onAdjustPaidLeave"];
  handleCreateNotice: NoticesSectionProps["actions"]["onCreateNotice"];
  handlePayrollDefinitionSave: PayrollSectionProps["actions"]["onPayrollDefinitionSave"];
  handlePayrollBatchCreate: PayrollSectionProps["actions"]["onPayrollBatchCreate"];
  openPayrollBatchDetail: PayrollSectionProps["actions"]["onOpenPayrollBatchDetail"];
  searchPayrollBatchDetail: PayrollSectionProps["actions"]["onSearchPayrollBatchDetail"];
  handleDeletePayrollBatch: PayrollSectionProps["actions"]["onDeletePayrollBatch"];
  handleExportPayrollBatch: PayrollSectionProps["actions"]["onExportPayrollBatch"];
  handleLoadAdminPayrollDetail: PayrollSectionProps["actions"]["onLoadAdminPayrollDetail"];
  handleAdminPayrollDownload: PayrollSectionProps["actions"]["onAdminPayrollDownload"];
  handlePayrollDownload: PayrollSectionProps["actions"]["onPayrollDownload"];
  handleDeletePayrollStatement: PayrollSectionProps["actions"]["onDeletePayrollStatement"];
  handleFileHistoryDownload: PayrollSectionProps["actions"]["onFileHistoryDownload"];
  handleMonthlyAttendanceCsvDownload: ReportsSectionProps["actions"]["onDownloadMonthlyAttendanceCsv"];
  handleDailyAttendanceCsvDownload: ReportsSectionProps["actions"]["onDownloadDailyAttendanceCsv"];
  handleDailyAttendancePdfDownload: ReportsSectionProps["actions"]["onDownloadDailyAttendancePdf"];
  handleMonthlyPayrollCsvDownload: ReportsSectionProps["actions"]["onDownloadMonthlyPayrollCsv"];
  handleMonthlyWorksPdfDownload: ReportsSectionProps["actions"]["onDownloadMonthlyWorksPdf"];
  handleSystemForm: SystemSectionProps["actions"]["onSystemForm"];
  applyAuditFilters: AuditSectionProps["actions"]["onApplyAuditFilters"];
  resetAuditFilters: AuditSectionProps["actions"]["onResetAuditFilters"];
  handleEmployeeLeaveRequestCreate: (payload: LeaveRequestCreatePayload) => Promise<void>;
  handleEmployeeAttendanceDailyEditRequestCreate: (payload: AttendanceDailyEditRequestCreatePayload) => Promise<void>;
  handleLoadEmployeePayrollDetail: EmployeePortalSectionProps["actions"]["onLoadEmployeePayrollDetail"];
  handleNotificationRead: EmployeePortalSectionProps["actions"]["onNotificationRead"];
};
