CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_code VARCHAR(30) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    kana VARCHAR(100),
    department_name VARCHAR(100),
    employment_type VARCHAR(30) NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('ACTIVE', 'SUSPENDED', 'RETIRED')),
    joined_on DATE NOT NULL,
    retired_on DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (retired_on IS NULL OR retired_on >= joined_on)
);

CREATE INDEX idx_employees_department_name ON employees (department_name);
CREATE INDEX idx_employees_status ON employees (status);

CREATE TABLE employee_auth (
    employee_id BIGINT PRIMARY KEY REFERENCES employees (id),
    login_id VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    password_updated_at TIMESTAMPTZ,
    last_login_at TIMESTAMPTZ,
    mobile_push_token VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE employee_cards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES employees (id),
    card_uid VARCHAR(64) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK ((is_active = TRUE AND revoked_at IS NULL) OR is_active = FALSE)
);

CREATE INDEX idx_employee_cards_employee_id ON employee_cards (employee_id);
CREATE UNIQUE INDEX uq_employee_cards_card_uid_active
    ON employee_cards (card_uid)
    WHERE is_active = TRUE;

CREATE TABLE attendance_devices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    location_name VARCHAR(100),
    os_user VARCHAR(100),
    app_version VARCHAR(30),
    device_secret_hash VARCHAR(255),
    last_seen_at TIMESTAMPTZ,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_attendance_devices_is_active ON attendance_devices (is_active);

CREATE TABLE attendance_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT REFERENCES employees (id),
    device_id BIGINT NOT NULL REFERENCES attendance_devices (id),
    card_uid VARCHAR(64) NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    event_type VARCHAR(20) CHECK (event_type IN ('CLOCK_IN', 'CLOCK_OUT')),
    source_type VARCHAR(20) NOT NULL CHECK (source_type IN ('CARD_READER')),
    receive_status VARCHAR(20) NOT NULL CHECK (receive_status IN ('ACCEPTED', 'REJECTED')),
    rejection_reason VARCHAR(100),
    offline_saved BOOLEAN NOT NULL DEFAULT FALSE,
    dedupe_key VARCHAR(100) UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_attendance_events_employee_occurred_at ON attendance_events (employee_id, occurred_at);
CREATE INDEX idx_attendance_events_device_occurred_at ON attendance_events (device_id, occurred_at);
CREATE INDEX idx_attendance_events_receive_status ON attendance_events (receive_status);
CREATE INDEX idx_attendance_events_card_uid ON attendance_events (card_uid);

CREATE TABLE attendance_daily (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES employees (id),
    target_date DATE NOT NULL,
    clock_in_at TIMESTAMPTZ,
    clock_out_at TIMESTAMPTZ,
    work_minutes INTEGER,
    late_flag BOOLEAN NOT NULL DEFAULT FALSE,
    early_leave_flag BOOLEAN NOT NULL DEFAULT FALSE,
    absence_flag BOOLEAN NOT NULL DEFAULT FALSE,
    special_leave_flag BOOLEAN NOT NULL DEFAULT FALSE,
    paid_leave_unit NUMERIC(4,2),
    remark VARCHAR(255),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (employee_id, target_date),
    CHECK (paid_leave_unit IS NULL OR paid_leave_unit IN (0.5, 1.0))
);

CREATE INDEX idx_attendance_daily_target_date ON attendance_daily (target_date);

CREATE TABLE leave_types (
    code VARCHAR(20) PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    requires_balance BOOLEAN NOT NULL,
    allows_half_day BOOLEAN NOT NULL,
    sort_order INTEGER NOT NULL
);

CREATE TABLE leave_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES employees (id),
    leave_type_code VARCHAR(20) NOT NULL REFERENCES leave_types (code),
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    day_unit VARCHAR(10) NOT NULL CHECK (day_unit IN ('FULL', 'HALF')),
    half_day_type VARCHAR(10) CHECK (half_day_type IN ('AM', 'PM')),
    quantity_days NUMERIC(4,2) NOT NULL,
    reason TEXT,
    status VARCHAR(20) NOT NULL CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'RETURNED')),
    approved_by BIGINT REFERENCES employees (id),
    approved_at TIMESTAMPTZ,
    decision_comment TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (start_date <= end_date),
    CHECK (
        (day_unit = 'HALF' AND start_date = end_date AND half_day_type IS NOT NULL AND quantity_days = 0.5)
        OR
        (day_unit = 'FULL' AND half_day_type IS NULL)
    )
);

CREATE INDEX idx_leave_requests_employee_created_at ON leave_requests (employee_id, created_at);
CREATE INDEX idx_leave_requests_status_start_date ON leave_requests (status, start_date);
CREATE INDEX idx_leave_requests_leave_type_code ON leave_requests (leave_type_code);

CREATE TABLE leave_request_actions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    leave_request_id BIGINT NOT NULL REFERENCES leave_requests (id),
    action_type VARCHAR(20) NOT NULL CHECK (action_type IN ('APPLIED', 'APPROVED', 'REJECTED', 'RETURNED')),
    action_by BIGINT NOT NULL REFERENCES employees (id),
    comment TEXT,
    acted_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_leave_request_actions_request_acted_at ON leave_request_actions (leave_request_id, acted_at);

CREATE TABLE paid_leave_grants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES employees (id),
    granted_on DATE NOT NULL,
    granted_days NUMERIC(4,2) NOT NULL,
    used_days NUMERIC(4,2) NOT NULL DEFAULT 0,
    expires_on DATE,
    note VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (granted_days >= 0),
    CHECK (used_days >= 0),
    CHECK (used_days <= granted_days)
);

CREATE INDEX idx_paid_leave_grants_employee_granted_on ON paid_leave_grants (employee_id, granted_on);
CREATE INDEX idx_paid_leave_grants_expires_on ON paid_leave_grants (expires_on);

CREATE TABLE payroll_statements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES employees (id),
    target_year_month CHAR(7) NOT NULL,
    file_path VARCHAR(255) NOT NULL,
    original_file_name VARCHAR(255) NOT NULL,
    file_size_bytes BIGINT,
    content_type VARCHAR(100),
    published_at TIMESTAMPTZ,
    uploaded_by BIGINT NOT NULL REFERENCES employees (id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (employee_id, target_year_month),
    CHECK (target_year_month ~ '^[0-9]{4}-[0-9]{2}$')
);

CREATE INDEX idx_payroll_statements_published_at ON payroll_statements (published_at);

CREATE TABLE payroll_statement_views (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payroll_statement_id BIGINT NOT NULL REFERENCES payroll_statements (id),
    employee_id BIGINT NOT NULL REFERENCES employees (id),
    viewed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ip_address VARCHAR(45),
    user_agent VARCHAR(255)
);

CREATE INDEX idx_payroll_statement_views_statement_viewed_at ON payroll_statement_views (payroll_statement_id, viewed_at);
CREATE INDEX idx_payroll_statement_views_employee_viewed_at ON payroll_statement_views (employee_id, viewed_at);

CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES employees (id),
    notification_type VARCHAR(30) NOT NULL,
    title VARCHAR(100) NOT NULL,
    body TEXT NOT NULL,
    related_type VARCHAR(30),
    related_id BIGINT,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    sent_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    read_at TIMESTAMPTZ
);

CREATE INDEX idx_notifications_employee_is_read_sent_at ON notifications (employee_id, is_read, sent_at);

CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_type VARCHAR(20) NOT NULL CHECK (actor_type IN ('EMPLOYEE', 'ADMIN', 'SYSTEM', 'DEVICE')),
    actor_id BIGINT,
    action VARCHAR(50) NOT NULL,
    target_type VARCHAR(50) NOT NULL,
    target_id VARCHAR(100),
    detail_json JSONB,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ip_address VARCHAR(45)
);

CREATE INDEX idx_audit_logs_occurred_at ON audit_logs (occurred_at);
CREATE INDEX idx_audit_logs_actor ON audit_logs (actor_type, actor_id);
CREATE INDEX idx_audit_logs_target ON audit_logs (target_type, target_id);
CREATE INDEX idx_audit_logs_detail_json ON audit_logs USING GIN (detail_json);

INSERT INTO leave_types (code, name, requires_balance, allows_half_day, sort_order)
VALUES
    ('PAID', '有給休暇', TRUE, TRUE, 1),
    ('ABSENCE', '欠勤', FALSE, FALSE, 2),
    ('SPECIAL', '特別休暇', FALSE, TRUE, 3);

